name: pyboqt
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - bzip2=1.0.8=h516909a_1
  - ca-certificates=2019.9.11=hecc5488_0
  - certifi=2019.9.11=py37_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=he1b5a44_1004
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=py37h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - icu=64.2=he1b5a44_1
  - importlib_metadata=0.23=py37_0
  - ipykernel=5.1.3=py37h5ca1d4c_0
  - ipython=7.9.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.2.0=py37_0
  - jupyter_client=5.3.3=py37_1
  - jupyter_core=4.6.1=py37_0
  - libclang=9.0.0=default_hde54327_4
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - libllvm9=9.0.0=hc9558a2_3
  - libpng=1.6.37=hed695b0_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.9.1=hebb1f50_0
  - libxml2=2.9.10=hee79883_0
  - libxslt=1.1.33=h31b3aaa_0
  - markupsafe=1.1.1=py37h516909a_0
  - mistune=0.8.4=py37h516909a_1000
  - more-itertools=7.2.0=py_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - notebook=6.0.1=py37_0
  - nspr=4.23=he1b5a44_0
  - nss=3.47=he751ad9_0
  - openssl=1.1.1d=h516909a_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - pcre=8.43=he1b5a44_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.3.1=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pygments=2.4.2=py_0
  - pyqt=5.12.3=py37hcca6a23_1
  - pyrsistent=0.15.5=py37h516909a_0
  - pyside2=5.13.1=py37hbee1fde_6
  - python=3.7.3=h33d41f4_1
  - python-dateutil=2.8.1=py_0
  - pyzmq=18.1.1=py37h1768529_0
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=hf8c457e_0
  - send2trash=1.5.0=py_0
  - setuptools=41.6.0=py37_1
  - six=1.13.0=py37_0
  - sqlite=3.30.1=hcee41ef_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.9=hed695b0_1003
  - tornado=6.0.3=py37h516909a_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_1001
  - zeromq=4.3.2=he1b5a44_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h516909a_1006
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: /home/tornado/miniconda3/envs/pyboqt

